apiVersion: apps/v1
kind: Deployment
metadata:
  name: upg-loadme
  namespace: demo
  labels:
    app: upg-loadme
spec:
  selector:
    matchLabels:
      app: upg-loadme
  replicas: 2
  template:
    metadata:
      name: upg-loadme-rs
      labels:
        app: upg-loadme
    spec:
      containers:
      - name: upg-loadme
        image: 458494077457.dkr.ecr.us-east-1.amazonaws.com/capstone-project-repo:v1 
        resources:
          requests:
            cpu: 800m
            memory: 400Mi
          limits:
            cpu: 1000m
            memory: 400Mi
        imagePullPolicy: Always

      restartPolicy: Always
      tolerations:
        - key: "special"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"




