apiVersion: v1
kind: Service
metadata:
  name: loadme-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
      app: upg-loadme
  ports:
    - protocol: TCP
      name: app-port
      port: 80
      targetPort: 8081
